apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: firefly-dataexchange
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  source:
    repoURL: https://hyperledger.github.io/firefly-helm-charts
    chart: firefly-dataexchange-https
    targetRevision: "*"
    helm:
      values: |
        nodeSelector:
          kubernetes.io/arch: amd64

        certificate:
          enabled: true
          issuerRef:
            kind: ClusterIssuer
            name: selfsigned-ca
        tlsSecret:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: firefly
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
