apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: paladin-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://lfdt-paladin.github.io/paladin
    chart: paladin-operator
    targetRevision: "0.15.0"
    helm:
      values: |
        mode: devnet
        nodeCount: {{ .Values.besu.nodeCount }}
        besuNodeCount: {{ .Values.besu.nodeCount }}
        installCRDs: true
        prometheus:
          enabled: false
        operator:
          nodeSelector:
            kubernetes.io/arch: amd64
        paladin:
          nodeNamePrefix: node
          image:
            repository: docker.io/lfdecentralizedtrust/paladin
            tag: {{ .Values.paladin.imageTag }}
            pullPolicy: Always
          baseNodePort: {{ .Values.paladin.baseNodePort }}
        besu:
          nodeNamePrefix: node
          image:
            repository: hyperledger/besu
            tag: {{ .Values.besu.imageTag }}
            pullPolicy: IfNotPresent
          baseNodePort: {{ .Values.besu.baseNodePort }}
        devnet:
          besuGenesis:
            chainID: {{ .Values.besu.chainId }}
  ignoreDifferences:
    - group: core.paladin.io
      kind: Paladin
      jsonPointers:
        - /spec/service/ports
    - group: core.paladin.io
      kind: Besu
      jsonPointers:
        - /spec/service/ports
  destination:
    server: https://kubernetes.default.svc
    namespace: paladin
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
