apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: firefly-cors-middleware
  namespace: argocd
  labels:
    app.kubernetes.io/name: firefly-cors-middleware
    app.kubernetes.io/part-of: firefly
spec:
  project: default
  source:
    repoURL: ${REPO_URL}
    targetRevision: ${REPO_REVISION}
    path: middleware/firefly
    directory:
      include: "values/firefly-cors-middleware.yaml"
      recurse: false
  destination:
    server: https://kubernetes.default.svc
    namespace: firefly
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  revisionHistoryLimit: 10
